error: try not to call a closure in the expression where it is declared
  --> $DIR/redundant_closure_call_fixable.rs:17:13
   |
LL |     let a = (|| 42)();
   |             ^^^^^^^^^ help: try doing something like: `42`
   |
   = note: `-D clippy::redundant-closure-call` implied by `-D warnings`

error: try not to call a closure in the expression where it is declared
  --> $DIR/redundant_closure_call_fixable.rs:18:13
   |
LL |       let b = (async || {
   |  _____________^
LL | |         let x = something().await;
LL | |         let y = something_else().await;
LL | |         x * y
LL | |     })();
   | |________^
   |
help: try doing something like
   |
LL ~     let b = async {
LL +         let x = something().await;
LL +         let y = something_else().await;
LL +         x * y
LL ~     };
   |

error: try not to call a closure in the expression where it is declared
  --> $DIR/redundant_closure_call_fixable.rs:23:13
   |
LL |       let c = (|| {
   |  _____________^
LL | |         let x = 21;
LL | |         let y = 2;
LL | |         x * y
LL | |     })();
   | |________^
   |
help: try doing something like
   |
LL ~     let c = {
LL +         let x = 21;
LL +         let y = 2;
LL +         x * y
LL ~     };
   |

error: try not to call a closure in the expression where it is declared
  --> $DIR/redundant_closure_call_fixable.rs:28:13
   |
LL |     let d = (async || something().await)();
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try doing something like: `async { something().await }`

error: try not to call a closure in the expression where it is declared
  --> $DIR/redundant_closure_call_fixable.rs:37:13
   |
LL |             (|| m!())()
   |             ^^^^^^^^^^^ help: try doing something like: `m!()`
...
LL |     m2!();
   |     ----- in this macro invocation
   |
   = note: this error originates in the macro `m2` (in Nightly builds, run with -Z macro-backtrace for more info)

error: try not to call a closure in the expression where it is declared
  --> $DIR/redundant_closure_call_fixable.rs:32:13
   |
LL |             (|| 0)()
   |             ^^^^^^^^ help: try doing something like: `0`
...
LL |     m2!();
   |     ----- in this macro invocation
   |
   = note: this error originates in the macro `m` which comes from the expansion of the macro `m2` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 6 previous errors

